const {JSDOM}=require('jsdom');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.join(__dirname,'..'),key='shici-notebook-v1';
const fixture={version:1,preferences:{split:59,fontSize:19,notesFontSize:16},articles:[{id:'article',title:'What is exploration? (15-1-3)',body:'We are all explorers.\n\nThe world has moved on.',translation:'',createdAt:'2026-09-21',updatedAt:'2026-09-21'}],words:[]};
const dom=new JSDOM(fs.readFileSync(path.join(root,'index.html'),'utf8'),{url:'http://127.0.0.1:4173/#study/article',runScripts:'outside-only',pretendToBeVisual:true});
const {window}=dom,document=window.document;
window.scrollTo=()=>{};
window.HTMLDialogElement.prototype.showModal=function(){this.open=true;};
window.HTMLDialogElement.prototype.close=function(){this.open=false;this.dispatchEvent(new window.Event('close'));};
const calls=[];
window.fetch=async(url,options)=>{calls.push({url,body:JSON.parse(options.body)});if(url.endsWith('/test'))return {ok:true,json:async()=>({ok:true,model:'deepseek-v4-pro'})};return {ok:true,json:async()=>({titleTranslation:'什么是探索？（15-1-3）',translation:'我们都是探索者。\n\n世界已经向前发展。',translationParagraphs:2,model:'deepseek-v4-pro'})};};
window.localStorage.setItem(key,JSON.stringify(fixture));
window.eval(fs.readFileSync(path.join(root,'i18n.js'),'utf8'));window.eval(fs.readFileSync(path.join(root,'app.js'),'utf8'));
const waitFor=async predicate=>{for(let i=0;i<30;i++){if(predicate())return;await new Promise(resolve=>setTimeout(resolve,0));}throw new Error(`Timed out waiting for UI; calls=${calls.map(call=>call.url).join(',')}; toast=${document.querySelector('#toast').textContent}`);};
(async()=>{try{
  const input=document.querySelector('#deepseek-api-key');input.value='sk-test-ui-secret';input.dispatchEvent(new window.Event('input',{bubbles:true}));
  assert.equal(window.localStorage.getItem('shici-deepseek-api-key'),'sk-test-ui-secret');
  assert.equal(window.sessionStorage.getItem('shici-deepseek-api-key'),null);
  document.querySelector('#test-deepseek').click();await waitFor(()=>document.querySelector('#deepseek-status').textContent.includes('连接正常'));
  assert.equal(calls[0].url,'/api/deepseek/test');assert.equal(calls[0].body.apiKey,'sk-test-ui-secret');
  document.querySelector('[data-translate-article]').click();await waitFor(()=>document.querySelector('#translation-dialog').open);
  assert.equal(calls[1].body.language,'zh-CN');
  assert.equal(calls[1].body.mode,'article');
  assert.equal(document.querySelector('#translation-title-preview').value,'什么是探索？（15-1-3）');
  assert.match(document.querySelector('#translation-preview').value,/我们都是探索者/);
  assert.equal(JSON.parse(window.localStorage.getItem(key)).articles[0].translation,'');
  document.querySelector('#save-translation').click();
  const saved=JSON.parse(window.localStorage.getItem(key));
  assert.equal(saved.articles[0].translationTitle,'什么是探索？（15-1-3）');assert.match(saved.articles[0].translation,/世界已经向前发展/);
  assert.equal(saved.preferences.showTranslation,true);assert.equal(document.querySelector('.article-title-translation').textContent,'什么是探索？（15-1-3）');
  assert.equal(window.localStorage.getItem(key).includes('sk-test-ui-secret'),false);
  const reloadDom=new JSDOM(fs.readFileSync(path.join(root,'index.html'),'utf8'),{url:'http://127.0.0.1:4173/#home',runScripts:'outside-only',pretendToBeVisual:true});
  const reloadWindow=reloadDom.window;reloadWindow.scrollTo=()=>{};reloadWindow.localStorage.setItem(key,JSON.stringify(saved));reloadWindow.localStorage.setItem('shici-deepseek-api-key','sk-test-ui-secret');
  reloadWindow.eval(fs.readFileSync(path.join(root,'i18n.js'),'utf8'));reloadWindow.eval(fs.readFileSync(path.join(root,'app.js'),'utf8'));
  assert.equal(reloadWindow.document.querySelector('#deepseek-api-key').value,'sk-test-ui-secret');
  assert.match(reloadWindow.document.querySelector('.api-privacy').textContent,/关闭或重启浏览器后仍保留/);
  reloadWindow.close();

  const migrationDom=new JSDOM(fs.readFileSync(path.join(root,'index.html'),'utf8'),{url:'http://127.0.0.1:4173/#home',runScripts:'outside-only',pretendToBeVisual:true});
  const migrationWindow=migrationDom.window;migrationWindow.scrollTo=()=>{};migrationWindow.localStorage.setItem(key,JSON.stringify(fixture));migrationWindow.sessionStorage.setItem('shici-deepseek-api-key','sk-legacy-session-secret');
  migrationWindow.eval(fs.readFileSync(path.join(root,'i18n.js'),'utf8'));migrationWindow.eval(fs.readFileSync(path.join(root,'app.js'),'utf8'));
  assert.equal(migrationWindow.localStorage.getItem('shici-deepseek-api-key'),'sk-legacy-session-secret');
  assert.equal(migrationWindow.sessionStorage.getItem('shici-deepseek-api-key'),null);
  migrationWindow.close();
  console.log('PASS: persistent API key with session migration, connection test, preview-before-save and bilingual title/body storage.');
}finally{window.close();}})().catch(error=>{console.error(error);process.exitCode=1;});
