// Run with jsdom available in the developer environment.
const {JSDOM}=require('jsdom');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.join(__dirname,'..');
const key='shici-notebook-v1';
const fixture={version:1,preferences:{split:59,fontSize:21,notesFontSize:16,showTranslation:false},articles:[{id:'article',title:'Original title',source:'Cambridge IELTS 15',body:'Learning in context.\n\nKeep the paragraphs.',translationTitle:'中文标题',translation:'在语境中学习。\n\n保留这些段落。',createdAt:'2026-09-20',updatedAt:'2026-09-20'}],words:[{id:'word',articleId:'article',term:'context',zh:'语境',en:'',note:'Saved note',context:'Learning in context.',createdAt:'2026-09-20',updatedAt:'2026-09-20'}]};
function open(saved=fixture){
  const dom=new JSDOM(fs.readFileSync(path.join(root,'index.html'),'utf8'),{url:'http://localhost/#study/article',runScripts:'outside-only',pretendToBeVisual:true});
  dom.window.scrollTo=()=>{};
  dom.window.localStorage.setItem(key,JSON.stringify(saved));
  dom.window.eval(fs.readFileSync(path.join(root,'i18n.js'),'utf8'));dom.window.eval(fs.readFileSync(path.join(root,'app.js'),'utf8'));
  return dom;
}
function fill(w,selector,value){const el=w.document.querySelector(selector);el.value=value;el.dispatchEvent(new w.Event('input',{bubbles:true}));}
function submit(w){w.document.querySelector('#inline-article-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));}
const dom=open(),w=dom.window,d=w.document;
try {
  assert.equal(d.querySelector('.study-word-item strong').textContent,'context');
  assert.equal(d.querySelector('.study-word-item small').textContent,'语境');
  assert.equal(d.querySelector('#article-text mark'),null);
  d.querySelector('[data-toggle-highlights]').click();
  assert.equal(d.querySelector('[data-toggle-highlights]').getAttribute('aria-checked'),'true');
  assert.equal(d.querySelector('#article-text mark').textContent,'context');
  assert.equal(d.querySelector('.article-translation'),null);
  d.querySelector('[data-toggle-translation]').click();
  assert.equal(d.querySelectorAll('.article-translation').length,2);
  assert.equal(d.querySelector('.article-title-translation').textContent,'中文标题');
  assert.match(d.querySelector('#article-text').textContent,/在语境中学习/);
  assert.equal(d.querySelector('[data-toggle-translation]').getAttribute('aria-checked'),'true');
  d.querySelector('[data-toggle-translation]').click();
  d.querySelector('[data-new-word]').click();
  assert.equal(d.querySelector('#word-term').getAttribute('placeholder'),null);
  assert.equal(d.querySelector('#word-zh').getAttribute('placeholder'),null);
  assert.equal(d.querySelector('#word-note').getAttribute('placeholder'),null);
  assert.equal(d.querySelector('#word-en'),null);
  assert.deepEqual([...d.querySelectorAll('#word-form textarea')].map(field=>field.name),['zh','note']);
  assert.match(d.querySelector('label[for="word-zh"]').textContent,/中文释义/);
  assert.match(d.querySelector('label[for="word-note"]').textContent,/笔记/);
  assert.equal(d.querySelector('.notes-body .article-words'),null);
  fill(w,'#word-term','learning');fill(w,'#word-note','Keep this unsaved right-pane draft');
  const noteForm=d.querySelector('#word-form');
  d.querySelector('[data-edit-article]').click();
  assert.ok(d.querySelector('.reading-pane #inline-article-form'));
  assert.equal(d.querySelector('#article-dialog').open,false);
  assert.equal(d.querySelector('#word-form'),noteForm);
  assert.equal(d.querySelector('#inline-article-body').value,fixture.articles[0].body);
  assert.equal(d.querySelector('#inline-article-source').value,fixture.articles[0].source);
  assert.equal(d.querySelector('#inline-article-translation-title').value,fixture.articles[0].translationTitle);
  assert.equal(d.querySelector('#inline-article-translation').value,fixture.articles[0].translation);
  fill(w,'#inline-article-title','Updated title');
  fill(w,'#inline-article-source','Cambridge IELTS 15 · Test 1');
  const updated='A new context.\n\nKeep <plain text> & punctuation.';
  fill(w,'#inline-article-body',updated);
  fill(w,'#inline-article-translation-title','更新后的中文标题');
  fill(w,'#inline-article-translation','更新后的译文。');
  const unload=new w.Event('beforeunload',{cancelable:true});w.dispatchEvent(unload);assert.equal(unload.defaultPrevented,true);
  submit(w);
  assert.equal(d.querySelector('#inline-article-form'),null);
  assert.equal(d.querySelector('#article-text').textContent,updated);
  assert.equal(d.querySelector('#article-text mark').textContent,'context');
  assert.equal(d.querySelector('#header-study h1').textContent,'Updated title');
  assert.equal(d.querySelector('#word-form'),noteForm);
  assert.equal(d.querySelector('#word-note').value,'Keep this unsaved right-pane draft');
  let saved=JSON.parse(w.localStorage.getItem(key));
  assert.equal(saved.articles[0].source,'Cambridge IELTS 15 · Test 1');assert.equal(saved.articles[0].body,updated);assert.equal(saved.articles[0].translationTitle,'更新后的中文标题');assert.equal(saved.articles[0].translation,'更新后的译文。');assert.equal(saved.words.length,2);assert.equal(saved.words[1].term,'learning');assert.equal(saved.words[1].note,'Keep this unsaved right-pane draft');
  const reloaded=open(saved);assert.equal(reloaded.window.document.querySelector('#article-text').textContent,updated);reloaded.window.close();
  d.querySelector('[data-edit-article]').click();fill(w,'#inline-article-body','Discard this change');
  d.querySelector('[data-cancel-article-edit]').click();
  assert.equal(d.querySelector('#article-text').textContent,updated);
  assert.equal(d.querySelector('#word-form'),noteForm);
  d.querySelector('[data-edit-article]').click();fill(w,'#inline-article-body','   ');submit(w);
  assert.ok(d.querySelector('#inline-article-form'));
  assert.equal(JSON.parse(w.localStorage.getItem(key)).articles[0].body,updated);
  fill(w,'#inline-article-body','Draft while browsing the library');
  w.location.hash='#articles';w.dispatchEvent(new w.HashChangeEvent('hashchange'));
  d.querySelector('[data-edit-article]').click();w.dispatchEvent(new w.HashChangeEvent('hashchange'));
  assert.equal(d.querySelector('#inline-article-body').value,'Draft while browsing the library');
  assert.equal(d.querySelector('#article-dialog').open,false);
  const originalSetItem=w.Storage.prototype.setItem;
  w.Storage.prototype.setItem=()=>{throw new Error('quota');};
  submit(w);
  assert.equal(d.querySelector('#inline-article-body').value,'Draft while browsing the library');
  assert.equal(JSON.parse(w.localStorage.getItem(key)).articles[0].body,updated);
  w.Storage.prototype.setItem=originalSetItem;
  submit(w);
  assert.equal(d.querySelector('#article-text').textContent,'Draft while browsing the library');
  const legacy=open({...fixture,words:[{...fixture.words[0],en:'Meaning from the old field'}]});
  legacy.window.document.querySelector('.study-word-item').click();
  assert.equal(legacy.window.document.querySelector('#word-note').value,'Saved note\n\n原英文释义\nMeaning from the old field');
  fill(legacy.window,'#word-zh','新的释义');
  const migrated=JSON.parse(legacy.window.localStorage.getItem(key)).words[0];
  assert.equal(migrated.note,'Saved note\n\n原英文释义\nMeaning from the old field');
  assert.equal('en' in migrated,false);
  legacy.window.close();
  console.log('PASS: inline edit, save/reload, paragraphs, escaping, highlights, note draft preservation, cancel, blank validation, navigation drafts, storage failure/retry.');
} finally {dom.window.close();}
