// Run with jsdom installed in the developer environment (not required by the app).
const {JSDOM}=require('jsdom');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.join(__dirname,'..');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const script=fs.readFileSync(path.join(root,'app.js'),'utf8');
const i18n=fs.readFileSync(path.join(root,'i18n.js'),'utf8');
const css=fs.readFileSync(path.join(root,'styles.css'),'utf8');
const key='shici-notebook-v1';
const fixture={version:1,preferences:{split:59,fontSize:21},articles:[{id:'test-reading',title:'Typography check',body:'Learning in context.',createdAt:'2026-09-20',updatedAt:'2026-09-20'}],words:[]};
function open(saved){
  const dom=new JSDOM(html,{url:'http://localhost/#study/test-reading',runScripts:'outside-only',pretendToBeVisual:true});
  const {window:w}=dom;w.scrollTo=()=>{};w.localStorage.setItem(key,JSON.stringify(saved));
  const style=w.document.createElement('style');style.textContent=css;w.document.head.append(style);
  w.eval(i18n);w.eval(script);return dom;
}
function edit(w,selector,value,event='input'){
  const el=w.document.querySelector(selector);assert.ok(el,selector);el.value=value;el.dispatchEvent(new w.Event(event,{bubbles:true}));return el;
}
(async()=>{
  const dom=open(fixture),w=dom.window,d=w.document;
  assert.equal(d.querySelector('.app-header .brand'),null);
  assert.equal(d.querySelector('.study-top,.reading-toolbar,.notes-header,.notes-font-toolbar'),null);
  assert.equal(d.querySelectorAll('[data-font-target]').length,6);
  assert.equal(d.querySelectorAll('[data-padding-target]').length,8);
  assert.equal(d.querySelectorAll('[data-line-height]').length,2);
  assert.equal(d.querySelectorAll('[data-reading-background]').length,8);
  assert.equal(d.querySelector('#settings-dialog').querySelectorAll('[data-font-target]').length,6);
  assert.equal(d.querySelector('#header-study h1').textContent,'Typography check');
  assert.equal(d.querySelector('#header-study-summary'),null);
  assert.equal(d.querySelector('#header-study-actions > .study-tools').open,false);
  assert.equal(d.querySelector('#header-study-actions [data-edit-article]').dataset.editArticle,'test-reading');
  assert.equal(d.querySelector('.article-reading-stats').textContent,'3 词 · 0 条笔记');
  assert.equal(d.querySelector('#settings-reading-font').value,'21');
  assert.equal(d.querySelector('#settings-notes-font').value,'16');
  assert.equal(d.querySelector('#settings-dictionary-font').value,'13.5');
  assert.equal(d.querySelector('label[for="settings-dictionary-font"]').textContent,'词典字号');
  assert.match(css,/\.longman-definition\{[^}]*font-size:var\(--dictionary-size,13\.5px\)/);
  assert.match(w.getComputedStyle(d.querySelector('#article-text')).fontFamily,/Arial/);
  d.querySelector('[data-new-word]').click();
  edit(w,'#word-term','context');edit(w,'#word-note','Unsaved draft stays intact.');
  edit(w,'#settings-reading-font','23.7');
  assert.equal(d.documentElement.style.getPropertyValue('--reading-size'),'23.7px');
  assert.equal(d.documentElement.style.getPropertyValue('--notes-size'),'16px');
  assert.equal(d.documentElement.style.getPropertyValue('--dictionary-size'),'13.5px');
  assert.equal(d.documentElement.style.getPropertyValue('--reading-line-height'),'1.95');
  assert.equal(d.documentElement.style.getPropertyValue('--reading-background'),'#ffffff');
  assert.equal(d.documentElement.style.getPropertyValue('--article-padding-top'),'24px');
  assert.equal(d.documentElement.style.getPropertyValue('--article-padding-right'),'40px');
  assert.equal(d.documentElement.style.getPropertyValue('--article-padding-bottom'),'48px');
  assert.equal(d.documentElement.style.getPropertyValue('--article-padding-left'),'40px');
  edit(w,'#settings-notes-font','18.4');
  assert.equal(d.documentElement.style.getPropertyValue('--notes-size'),'18.4px');
  assert.equal(d.documentElement.style.getPropertyValue('--dictionary-size'),'13.5px');
  edit(w,'#settings-dictionary-font','19.2');
  assert.equal(d.documentElement.style.getPropertyValue('--dictionary-size'),'19.2px');
  assert.equal(d.documentElement.style.getPropertyValue('--notes-size'),'18.4px');
  edit(w,'#settings-padding-left','18');
  assert.equal(d.documentElement.style.getPropertyValue('--article-padding-left'),'18px');
  edit(w,'#settings-line-height','2.35');
  assert.equal(d.documentElement.style.getPropertyValue('--reading-line-height'),'2.35');
  d.querySelector('[data-reading-background="green"]').click();
  assert.equal(d.documentElement.style.getPropertyValue('--reading-background'),'#eef6e8');
  assert.equal(d.querySelector('[data-reading-background="green"]').getAttribute('aria-checked'),'true');
  assert.match(css,/html,body,#app,\.page,\.app-header/);
  assert.match(css,/\.article-card,\.word-table,\.word-row/);
  assert.match(css,/body\{min-height:100vh;min-height:100dvh;display:flex;flex-direction:column/);
  assert.match(css,/#app\{width:100%;min-height:calc\(100vh - var\(--header-height\)\);min-height:calc\(100dvh - var\(--header-height\)\);flex:1 0 auto/);
  assert.match(css,/\.page\{min-height:calc\(100vh - var\(--header-height\)\);min-height:calc\(100dvh - var\(--header-height\)\)\}/);
  assert.equal(d.querySelector('#word-note').value,'Unsaved draft stays intact.');
  await new Promise(resolve=>setTimeout(resolve,250));
  const saved=JSON.parse(w.localStorage.getItem(key));
  assert.equal(saved.preferences.fontSize,23.7);assert.equal(saved.preferences.notesFontSize,18.4);assert.equal(saved.preferences.dictionaryFontSize,19.2);assert.equal(saved.preferences.readingPaddingLeft,18);assert.equal(saved.preferences.readingLineHeight,2.35);assert.equal(saved.preferences.readingBackground,'green');
  assert.deepEqual(saved.articles,[{...fixture.articles[0],source:'',translationTitle:'',translation:''}]);assert.equal(saved.words.length,1);assert.equal(saved.words[0].note,'Unsaved draft stays intact.');
  assert.equal(d.querySelector('#notes-count').textContent,'1');
  assert.equal(d.querySelector('#word-save'),null);
  assert.ok(d.querySelector('#word-form'));
  d.querySelector('#word-back').click();
  assert.equal(d.querySelector('#word-form'),null);
  assert.equal(d.querySelector('.study-word-item strong').textContent,'context');
  assert.equal(d.querySelector('.study-word-item small').textContent,'—');
  d.querySelector('.study-word-item').click();
  assert.equal(d.querySelector('#word-note').value,'Unsaved draft stays intact.');
  w.location.hash='#home';w.dispatchEvent(new w.HashChangeEvent('hashchange'));
  assert.equal(d.querySelector('#header-study').hidden,true);
  assert.equal(d.querySelector('#header-study-actions').hidden,true);
  const reloaded=open(saved),w2=reloaded.window,d2=w2.document;
  assert.equal(d2.querySelector('#settings-reading-font').value,'23.7');
  assert.equal(d2.querySelector('#settings-notes-font').value,'18.4');
  assert.equal(d2.querySelector('#settings-dictionary-font').value,'19.2');
  assert.equal(d2.documentElement.style.getPropertyValue('--dictionary-size'),'19.2px');
  assert.equal(d2.querySelector('#settings-padding-left').value,'18');
  assert.equal(d2.querySelector('#settings-line-height').value,'2.35');
  assert.equal(d2.querySelector('[data-reading-background="green"]').getAttribute('aria-checked'),'true');
  edit(w2,'input[type=number][data-font-target=notes]','999','change');
  assert.equal(d2.querySelector('#settings-notes-font').value,'48');
  edit(w2,'input[type=number][data-font-target=notes]','','change');
  assert.equal(d2.querySelector('#settings-notes-font').value,'48');
  edit(w2,'input[type=number][data-font-target=reading]','12.1');
  w2.dispatchEvent(new w2.Event('beforeunload'));
  assert.equal(JSON.parse(w2.localStorage.getItem(key)).preferences.fontSize,12.1);
  assert.equal(d2.querySelector('#settings-reading-font').value,'12.1');
  dom.window.close();reloaded.window.close();
  console.log('PASS: legacy data, Arial, independent fractional sizes, draft retention, autosave, reload, bounds and unload persistence.');
})().catch(error=>{console.error(error);process.exitCode=1;});
